# version: '3.8'
# services:
#   backend:
#     image: ilhammuhamad/pm-be:build-${BUILD_NUMBER}
#     container_name: pm-be
#     ports:
#       - "3001:3001"
#     env_file:
#       - .env
#     environment:
#       - DATABASE_URL=${DATABASE_URL}
#     restart: unless-stopped

version: '3.8'
services:
  backend:
    image: ilhammuhamad/pm-be:build-${IMAGE_TAG}  # Gunakan tag image dari Jenkins
    container_name: pm-be
    ports:
      - "${PORT}:${PORT}"  # Gunakan port dari variabel lingkungan
    env_file:
      - ${ENV_FILE}  # Menggunakan file .env sesuai dengan branch (dev atau prod)
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}  # Menggunakan PORT sebagai environment variable
    restart: unless-stopped
